### ISSUE TITLE
Drag and drop of more than one sfv-file at once only checks one of them

### ISSUE THREAD

**Issue by hurda** [OV2/RapidCRC-Unicode#15]
When dragging a selection with more than one sfv-file (probably also applies to other checksum-files) into the RapidCRC-window, it's only checking one of them.

**Comment by OV2** [comment]
This can now be done by dragging files via the right mouse button, or by holding ctrl when dropping files onto the main window (popup menu will appear with an appropriate option).

**Comment by Cpuroast** [comment]
Can there be option, so this becomes the default behaviour, so that a modifier key doesn't have to be used? I often use rapidcrc-unicode on macOS using Wine, and it doesn't handle ctrl dragging to the rapid-crc window or right-button dragging them over. I haven't found a native mac application that even comes close to RapidCRC-Unicode.

The other simpler possibility would be to make it the default behaviour, without an option, I think most people that drag/drop multiple checksum files(sfv, md5, sha, etc) to the window expect all of them to be checked, not just one.
