### ISSUE TITLE
"How to create..." window appears whenever a new hash is calculated (0.3.35)

### ISSUE THREAD

**Issue by pkt01** [OV2/RapidCRC-Unicode#86]
Hello OV2,

Just updated from 0.3.34 to 0.3.35 and noticed that after calculating a file hash, the "How to create..." window immediately pops up, whereas in previous versions the default behavior was to show nothing -- it was up to the user what to do next: either copy to the clipboard or create a list, which is when the "How to create..." window used to appear.

Example: 
Unmark all algorithms in Options -> drag 'n' drop a file to RapidCRC ->  click CRC/MD5/SHA1/whatever.
 - Version 0.3.34: calculates and stop;
 - Version 0.3.35: calculates and then shows the aforementioned window.

What I'd like to ask is if this is the intended behaviour and, in case it is, if it's possible to add a toggle to revert/shut it down or some kind of workaround.

Thanks.

Additional info:
- OS: Windows 7 and Windows 10, both x64
- RapidCRC Unicode: 0.3.35 x64, portable

**Comment by OV2** [comment]
You are clicking on a button that says "Create XYZ file". If you did not calculate the necessary hash before, it asks you if you want to calculate it. In older versions it then stopped, but since you already indicated you want to create an XYZ file, it now directly shows the dialog. (https://github.com/OV2/RapidCRC-Unicode/issues/78#issuecomment-754764228)

I could add a new Calculate" submenu to the context menu of the list, which then offers all algorithms to trigger a calculation. Would that be ok for your use-case?

**Comment by pkt01** [comment]
Ah, it was a design change then. Wasn't sure if it was the correct behaviour or some kind of bug, hence why I reported here. 

Your solution would be great, OV2, if it isn't too troublesome to implement. I understand most people use RapidCRC Unicode to bulk calculate/verify files, which I do too, but I also use it to quickly get a hash of a single file and then copy/paste the value somewhere else; been doing this for years.

Anyway, thank you for your attention.
